name: Release

on:
  push:
    branches: [master]
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - shell: bash
        run: |
          pnpm i --frozen-lockfile
          pnpm -r build
          rm -rf cmd/main/build
          cp -r control-panel/build cmd/main
          ./build_dist.sh
        # execname=pear-desktop-twitch-song-requests_${{ matrix.os.name }}_${{ matrix.os.arch }}
        # if [ "${{ matrix.os.name }}" = 'windows' ]; then execname="${execname}.exe"; fi
        # CGO_ENABLED=0 GOOS=${{ matrix.os.name }} GOARCH=${{ matrix.os.arch }} go build -ldflags="-s -w" -trimpath -o "$execname" cmd/main/*.go
      - uses: actions/upload-artifact@v4
        if: github.ref_type != 'tag'
        with:
          name: pear-desktop-twitch-song-requests_${{ matrix.os.name }}_${{ matrix.os.arch }}
          path: pear-desktop-twitch-song-requests_*
      - id: version-tag-ref
        if: github.ref_type == 'tag'
        run: |
          ref="${{ github.ref }}"
          mv pear-desktop-twitch-song-requests_linux_amd64 pear-desktop-twitch-song-requests_linux_amd64-${ref#refs/tags/}
          mv pear-desktop-twitch-song-requests_linux_arm64 pear-desktop-twitch-song-requests_linux_arm64-${ref#refs/tags/}
          mv pear-desktop-twitch-song-requests_windows_amd64.exe pear-desktop-twitch-song-requests_windows_amd64-${ref#refs/tags/}.exe
          mv pear-desktop-twitch-song-requests_windows_arm64.exe pear-desktop-twitch-song-requests_windows_arm64-${ref#refs/tags/}.exe
          mv pear-desktop-twitch-song-requests_darwin_amd64 pear-desktop-twitch-song-requests_darwin_amd64-${ref#refs/tags/}
          mv pear-desktop-twitch-song-requests_darwin_arm64 pear-desktop-twitch-song-requests_darwin_arm64-${ref#refs/tags/}
          echo "ref=${ref#refs/tags/}" >>"$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.version-tag-ref.outputs.ref }}
          prerelease: ${{ contains(github.ref, '-rc') }}
          make_latest: true
          generate_release_notes: true
          preserve_order: true
          fail_on_unmatched_files: true
          files: |
            pear-desktop-twitch-song-requests_windows_amd64-${{ steps.version-tag-ref.outputs.ref }}.exe
            pear-desktop-twitch-song-requests_windows_arm64-${{ steps.version-tag-ref.outputs.ref }}.exe
            pear-desktop-twitch-song-requests_linux_amd64-${{ steps.version-tag-ref.outputs.ref }}
            pear-desktop-twitch-song-requests_linux_arm64-${{ steps.version-tag-ref.outputs.ref }}
            pear-desktop-twitch-song-requests_darwin_amd64-${{ steps.version-tag-ref.outputs.ref }}
            pear-desktop-twitch-song-requests_darwin_arm64-${{ steps.version-tag-ref.outputs.ref }}
